// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Sales.API.Data;

#nullable disable

namespace Sales.API.Migrations
{
    [DbContext(typeof(SalesContext))]
    [Migration("20250821182846_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("Sales.API.Models.Order", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("CustomerEmail")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<string>("CustomerName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<DateTime>("OrderDate")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<decimal>("TotalAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.ToTable("Orders");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2025, 8, 20, 18, 28, 45, 148, DateTimeKind.Utc).AddTicks(2483),
                            CustomerEmail = "joao.silva@email.com",
                            CustomerName = "João Silva",
                            OrderDate = new DateTime(2025, 8, 20, 18, 28, 45, 148, DateTimeKind.Utc).AddTicks(1819),
                            Status = "Confirmed",
                            TotalAmount = 4585.90m,
                            UpdatedAt = new DateTime(2025, 8, 20, 18, 28, 45, 148, DateTimeKind.Utc).AddTicks(2620)
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2025, 8, 21, 18, 28, 45, 148, DateTimeKind.Utc).AddTicks(2745),
                            CustomerEmail = "maria.santos@email.com",
                            CustomerName = "Maria Santos",
                            OrderDate = new DateTime(2025, 8, 21, 18, 28, 45, 148, DateTimeKind.Utc).AddTicks(2744),
                            Status = "Pending",
                            TotalAmount = 405.90m,
                            UpdatedAt = new DateTime(2025, 8, 21, 18, 28, 45, 148, DateTimeKind.Utc).AddTicks(2745)
                        });
                });

            modelBuilder.Entity("Sales.API.Models.OrderItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("OrderId")
                        .HasColumnType("int");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<string>("ProductName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<decimal>("UnitPrice")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("OrderId");

                    b.ToTable("OrderItems");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            OrderId = 1,
                            ProductId = 1,
                            ProductName = "Notebook Dell",
                            Quantity = 1,
                            UnitPrice = 4500.00m
                        },
                        new
                        {
                            Id = 2,
                            OrderId = 1,
                            ProductId = 2,
                            ProductName = "Mouse Sem Fio",
                            Quantity = 1,
                            UnitPrice = 85.90m
                        },
                        new
                        {
                            Id = 3,
                            OrderId = 2,
                            ProductId = 3,
                            ProductName = "Teclado Mecânico",
                            Quantity = 1,
                            UnitPrice = 320.00m
                        },
                        new
                        {
                            Id = 4,
                            OrderId = 2,
                            ProductId = 2,
                            ProductName = "Mouse Sem Fio",
                            Quantity = 1,
                            UnitPrice = 85.90m
                        });
                });

            modelBuilder.Entity("Sales.API.Models.OrderItem", b =>
                {
                    b.HasOne("Sales.API.Models.Order", "Order")
                        .WithMany("OrderItems")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Order");
                });

            modelBuilder.Entity("Sales.API.Models.Order", b =>
                {
                    b.Navigation("OrderItems");
                });
#pragma warning restore 612, 618
        }
    }
}
