// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Stock.API.Data;

#nullable disable

namespace Stock.API.Migrations
{
    [DbContext(typeof(StockContext))]
    partial class StockContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("Stock.API.Models.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("QuantityInStock")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2025, 8, 20, 18, 40, 38, 542, DateTimeKind.Utc).AddTicks(4309),
                            Description = "Notebook Dell Inspiron 15",
                            Name = "Notebook Dell",
                            Price = 4500.00m,
                            QuantityInStock = 100,
                            UpdatedAt = new DateTime(2025, 8, 20, 18, 40, 38, 542, DateTimeKind.Utc).AddTicks(4314)
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2025, 8, 20, 18, 40, 38, 542, DateTimeKind.Utc).AddTicks(5239),
                            Description = "Mouse óptico sem fio",
                            Name = "Mouse Sem Fio",
                            Price = 85.90m,
                            QuantityInStock = 200,
                            UpdatedAt = new DateTime(2025, 8, 20, 18, 40, 38, 542, DateTimeKind.Utc).AddTicks(5240)
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2025, 8, 20, 18, 40, 38, 542, DateTimeKind.Utc).AddTicks(5242),
                            Description = "Teclado mecânico RGB",
                            Name = "Teclado Mecânico",
                            Price = 320.00m,
                            QuantityInStock = 75,
                            UpdatedAt = new DateTime(2025, 8, 20, 18, 40, 38, 542, DateTimeKind.Utc).AddTicks(5242)
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
